### ISSUE TITLE
Using snippet strips out dollar signs

### ISSUE THREAD

**Issue by vongoh** [jugyo/SublimeSnippetMaker#6]
I installed from package control and tried my first test snippet on this straightforward `border-radius` mixin.   The page is saved as `_global.scss`:

``` scss
@mixin radius($radius:$global-radius) {
  @if $radius {
    @if $experimental {
      -webkit-border-radius: $radius;
    }
    border-radius: $radius;
  }
```

I set the trigger to "rds" and tried it.   What I get back on the screen looks like this:

``` scss
@mixin radius(:-radius) {
  @if  {
    @if  {
      -webkit-border-radius: ;
    }
    border-radius: ;
  }
}
```

Any ideas?
